name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch: # This enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Git user and email
        run: |
          git config --global user.email "omparkhomchuk@gmail.com "
          git config --global user.name "omparkhomchuk"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p '*_test.py'

      - name: Run linters (example: flake8)
        run: |
          pip install flake8
          flake8 .

      - name: Run database migrations (if applicable)
        run: |
          # Add commands to run database migrations here, if applicable
          # Example: python manage.py migrate

      - name: Deploy to server (if applicable)
        run: |
          # Add commands to deploy your application to a server, if applicable
          # Example: scp -r . username@server_ip:/path/to/app

      - name: Update code in repository
        run: |
          git add .
          git commit -m "CI: Update code"
          git push
